thematic: "Produit"
questions:
  - text: "Avez-vous mis en place un système de suivi des erreurs utilisateurs (Sentry, Rollbar, Bugsnag) ?"
    description: "Monitoring des erreurs en production, alertes, analyse des crashs. Essentiel pour identifier et résoudre rapidement les problèmes."
  
  - text: "Collectez-vous des métriques d'usage (analytics) pour comprendre l'utilisation du produit ?"
    description: "Métriques d'utilisation, parcours utilisateur, points de friction. Essentiel pour prendre des décisions data-driven."
  
  - text: "Avez-vous un système de feedback utilisateur intégré (formulaires, tickets, NPS) ?"
    description: "Mécanisme pour recueillir les retours utilisateurs, NPS, enquêtes. Essentiel pour l'amélioration continue."
  
  - text: "Avez-vous mis en place des tests d'acceptation utilisateur (UAT) avec de vrais utilisateurs ?"
    description: "Tests avec de vrais utilisateurs avant mise en production. Valide l'expérience utilisateur et réduit les risques."
  
  - text: "Collectez-vous des métriques business (conversion, rétention, engagement) pour mesurer le succès ?"
    description: "Métriques business pour mesurer l'impact des fonctionnalités et prendre des décisions stratégiques."

